import torch

from athena import Athena
from hfmodel import load_hfmodel
from utils import EmptyInitOnDevice

print("Initializing athena...")
with EmptyInitOnDevice('cpu'):
    athena = Athena()

print("Initializing hfmodel...")
hfmodel = load_hfmodel()

print("Transfering weights...")
hfmodel_to_athena = {
    "model.embed_tokens.weight" : "table.weight",
    "model.layers.0.self_attn.o_proj.weight" : "sas.0.out_proj.weight",
    "model.layers.0.self_attn.qkv_proj.weight" : "sas.0.qkv_proj.weight",
    "model.layers.0.mlp.gate_up_proj.weight" : "ffns.0.up_proj.weight",
    "model.layers.0.mlp.down_proj.weight" : "ffns.0.down_proj.weight",
    "model.layers.0.input_layernorm.weight" : "sas.0.norm.weight",
    "model.layers.0.post_attention_layernorm.weight" : "ffns.0.norm.weight",
    "model.layers.1.self_attn.o_proj.weight" : "sas.1.out_proj.weight",
    "model.layers.1.self_attn.qkv_proj.weight" : "sas.1.qkv_proj.weight",
    "model.layers.1.mlp.gate_up_proj.weight" : "ffns.1.up_proj.weight",
    "model.layers.1.mlp.down_proj.weight" : "ffns.1.down_proj.weight",
    "model.layers.1.input_layernorm.weight" : "sas.1.norm.weight",
    "model.layers.1.post_attention_layernorm.weight" : "ffns.1.norm.weight",
    "model.layers.2.self_attn.o_proj.weight" : "sas.2.out_proj.weight",
    "model.layers.2.self_attn.qkv_proj.weight" : "sas.2.qkv_proj.weight",
    "model.layers.2.mlp.gate_up_proj.weight" : "ffns.2.up_proj.weight",
    "model.layers.2.mlp.down_proj.weight" : "ffns.2.down_proj.weight",
    "model.layers.2.input_layernorm.weight" : "sas.2.norm.weight",
    "model.layers.2.post_attention_layernorm.weight" : "ffns.2.norm.weight",
    "model.layers.3.self_attn.o_proj.weight" : "sas.3.out_proj.weight",
    "model.layers.3.self_attn.qkv_proj.weight" : "sas.3.qkv_proj.weight",
    "model.layers.3.mlp.gate_up_proj.weight" : "ffns.3.up_proj.weight",
    "model.layers.3.mlp.down_proj.weight" : "ffns.3.down_proj.weight",
    "model.layers.3.input_layernorm.weight" : "sas.3.norm.weight",
    "model.layers.3.post_attention_layernorm.weight" : "ffns.3.norm.weight",
    "model.layers.4.self_attn.o_proj.weight" : "sas.4.out_proj.weight",
    "model.layers.4.self_attn.qkv_proj.weight" : "sas.4.qkv_proj.weight",
    "model.layers.4.mlp.gate_up_proj.weight" : "ffns.4.up_proj.weight",
    "model.layers.4.mlp.down_proj.weight" : "ffns.4.down_proj.weight",
    "model.layers.4.input_layernorm.weight" : "sas.4.norm.weight",
    "model.layers.4.post_attention_layernorm.weight" : "ffns.4.norm.weight",
    "model.layers.5.self_attn.o_proj.weight" : "sas.5.out_proj.weight",
    "model.layers.5.self_attn.qkv_proj.weight" : "sas.5.qkv_proj.weight",
    "model.layers.5.mlp.gate_up_proj.weight" : "ffns.5.up_proj.weight",
    "model.layers.5.mlp.down_proj.weight" : "ffns.5.down_proj.weight",
    "model.layers.5.input_layernorm.weight" : "sas.5.norm.weight",
    "model.layers.5.post_attention_layernorm.weight" : "ffns.5.norm.weight",
    "model.layers.6.self_attn.o_proj.weight" : "sas.6.out_proj.weight",
    "model.layers.6.self_attn.qkv_proj.weight" : "sas.6.qkv_proj.weight",
    "model.layers.6.mlp.gate_up_proj.weight" : "ffns.6.up_proj.weight",
    "model.layers.6.mlp.down_proj.weight" : "ffns.6.down_proj.weight",
    "model.layers.6.input_layernorm.weight" : "sas.6.norm.weight",
    "model.layers.6.post_attention_layernorm.weight" : "ffns.6.norm.weight",
    "model.layers.7.self_attn.o_proj.weight" : "sas.7.out_proj.weight",
    "model.layers.7.self_attn.qkv_proj.weight" : "sas.7.qkv_proj.weight",
    "model.layers.7.mlp.gate_up_proj.weight" : "ffns.7.up_proj.weight",
    "model.layers.7.mlp.down_proj.weight" : "ffns.7.down_proj.weight",
    "model.layers.7.input_layernorm.weight" : "sas.7.norm.weight",
    "model.layers.7.post_attention_layernorm.weight" : "ffns.7.norm.weight",
    "model.layers.8.self_attn.o_proj.weight" : "sas.8.out_proj.weight",
    "model.layers.8.self_attn.qkv_proj.weight" : "sas.8.qkv_proj.weight",
    "model.layers.8.mlp.gate_up_proj.weight" : "ffns.8.up_proj.weight",
    "model.layers.8.mlp.down_proj.weight" : "ffns.8.down_proj.weight",
    "model.layers.8.input_layernorm.weight" : "sas.8.norm.weight",
    "model.layers.8.post_attention_layernorm.weight" : "ffns.8.norm.weight",
    "model.layers.9.self_attn.o_proj.weight" : "sas.9.out_proj.weight",
    "model.layers.9.self_attn.qkv_proj.weight" : "sas.9.qkv_proj.weight",
    "model.layers.9.mlp.gate_up_proj.weight" : "ffns.9.up_proj.weight",
    "model.layers.9.mlp.down_proj.weight" : "ffns.9.down_proj.weight",
    "model.layers.9.input_layernorm.weight" : "sas.9.norm.weight",
    "model.layers.9.post_attention_layernorm.weight" : "ffns.9.norm.weight",
    "model.layers.10.self_attn.o_proj.weight" : "sas.10.out_proj.weight",
    "model.layers.10.self_attn.qkv_proj.weight" : "sas.10.qkv_proj.weight",
    "model.layers.10.mlp.gate_up_proj.weight" : "ffns.10.up_proj.weight",
    "model.layers.10.mlp.down_proj.weight" : "ffns.10.down_proj.weight",
    "model.layers.10.input_layernorm.weight" : "sas.10.norm.weight",
    "model.layers.10.post_attention_layernorm.weight" : "ffns.10.norm.weight",
    "model.layers.11.self_attn.o_proj.weight" : "sas.11.out_proj.weight",
    "model.layers.11.self_attn.qkv_proj.weight" : "sas.11.qkv_proj.weight",
    "model.layers.11.mlp.gate_up_proj.weight" : "ffns.11.up_proj.weight",
    "model.layers.11.mlp.down_proj.weight" : "ffns.11.down_proj.weight",
    "model.layers.11.input_layernorm.weight" : "sas.11.norm.weight",
    "model.layers.11.post_attention_layernorm.weight" : "ffns.11.norm.weight",
    "model.layers.12.self_attn.o_proj.weight" : "sas.12.out_proj.weight",
    "model.layers.12.self_attn.qkv_proj.weight" : "sas.12.qkv_proj.weight",
    "model.layers.12.mlp.gate_up_proj.weight" : "ffns.12.up_proj.weight",
    "model.layers.12.mlp.down_proj.weight" : "ffns.12.down_proj.weight",
    "model.layers.12.input_layernorm.weight" : "sas.12.norm.weight",
    "model.layers.12.post_attention_layernorm.weight" : "ffns.12.norm.weight",
    "model.layers.13.self_attn.o_proj.weight" : "sas.13.out_proj.weight",
    "model.layers.13.self_attn.qkv_proj.weight" : "sas.13.qkv_proj.weight",
    "model.layers.13.mlp.gate_up_proj.weight" : "ffns.13.up_proj.weight",
    "model.layers.13.mlp.down_proj.weight" : "ffns.13.down_proj.weight",
    "model.layers.13.input_layernorm.weight" : "sas.13.norm.weight",
    "model.layers.13.post_attention_layernorm.weight" : "ffns.13.norm.weight",
    "model.layers.14.self_attn.o_proj.weight" : "sas.14.out_proj.weight",
    "model.layers.14.self_attn.qkv_proj.weight" : "sas.14.qkv_proj.weight",
    "model.layers.14.mlp.gate_up_proj.weight" : "ffns.14.up_proj.weight",
    "model.layers.14.mlp.down_proj.weight" : "ffns.14.down_proj.weight",
    "model.layers.14.input_layernorm.weight" : "sas.14.norm.weight",
    "model.layers.14.post_attention_layernorm.weight" : "ffns.14.norm.weight",
    "model.layers.15.self_attn.o_proj.weight" : "sas.15.out_proj.weight",
    "model.layers.15.self_attn.qkv_proj.weight" : "sas.15.qkv_proj.weight",
    "model.layers.15.mlp.gate_up_proj.weight" : "ffns.15.up_proj.weight",
    "model.layers.15.mlp.down_proj.weight" : "ffns.15.down_proj.weight",
    "model.layers.15.input_layernorm.weight" : "sas.15.norm.weight",
    "model.layers.15.post_attention_layernorm.weight" : "ffns.15.norm.weight",
    "model.layers.16.self_attn.o_proj.weight" : "sas.16.out_proj.weight",
    "model.layers.16.self_attn.qkv_proj.weight" : "sas.16.qkv_proj.weight",
    "model.layers.16.mlp.gate_up_proj.weight" : "ffns.16.up_proj.weight",
    "model.layers.16.mlp.down_proj.weight" : "ffns.16.down_proj.weight",
    "model.layers.16.input_layernorm.weight" : "sas.16.norm.weight",
    "model.layers.16.post_attention_layernorm.weight" : "ffns.16.norm.weight",
    "model.layers.17.self_attn.o_proj.weight" : "sas.17.out_proj.weight",
    "model.layers.17.self_attn.qkv_proj.weight" : "sas.17.qkv_proj.weight",
    "model.layers.17.mlp.gate_up_proj.weight" : "ffns.17.up_proj.weight",
    "model.layers.17.mlp.down_proj.weight" : "ffns.17.down_proj.weight",
    "model.layers.17.input_layernorm.weight" : "sas.17.norm.weight",
    "model.layers.17.post_attention_layernorm.weight" : "ffns.17.norm.weight",
    "model.layers.18.self_attn.o_proj.weight" : "sas.18.out_proj.weight",
    "model.layers.18.self_attn.qkv_proj.weight" : "sas.18.qkv_proj.weight",
    "model.layers.18.mlp.gate_up_proj.weight" : "ffns.18.up_proj.weight",
    "model.layers.18.mlp.down_proj.weight" : "ffns.18.down_proj.weight",
    "model.layers.18.input_layernorm.weight" : "sas.18.norm.weight",
    "model.layers.18.post_attention_layernorm.weight" : "ffns.18.norm.weight",
    "model.layers.19.self_attn.o_proj.weight" : "sas.19.out_proj.weight",
    "model.layers.19.self_attn.qkv_proj.weight" : "sas.19.qkv_proj.weight",
    "model.layers.19.mlp.gate_up_proj.weight" : "ffns.19.up_proj.weight",
    "model.layers.19.mlp.down_proj.weight" : "ffns.19.down_proj.weight",
    "model.layers.19.input_layernorm.weight" : "sas.19.norm.weight",
    "model.layers.19.post_attention_layernorm.weight" : "ffns.19.norm.weight",
    "model.layers.20.self_attn.o_proj.weight" : "sas.20.out_proj.weight",
    "model.layers.20.self_attn.qkv_proj.weight" : "sas.20.qkv_proj.weight",
    "model.layers.20.mlp.gate_up_proj.weight" : "ffns.20.up_proj.weight",
    "model.layers.20.mlp.down_proj.weight" : "ffns.20.down_proj.weight",
    "model.layers.20.input_layernorm.weight" : "sas.20.norm.weight",
    "model.layers.20.post_attention_layernorm.weight" : "ffns.20.norm.weight",
    "model.layers.21.self_attn.o_proj.weight" : "sas.21.out_proj.weight",
    "model.layers.21.self_attn.qkv_proj.weight" : "sas.21.qkv_proj.weight",
    "model.layers.21.mlp.gate_up_proj.weight" : "ffns.21.up_proj.weight",
    "model.layers.21.mlp.down_proj.weight" : "ffns.21.down_proj.weight",
    "model.layers.21.input_layernorm.weight" : "sas.21.norm.weight",
    "model.layers.21.post_attention_layernorm.weight" : "ffns.21.norm.weight",
    "model.layers.22.self_attn.o_proj.weight" : "sas.22.out_proj.weight",
    "model.layers.22.self_attn.qkv_proj.weight" : "sas.22.qkv_proj.weight",
    "model.layers.22.mlp.gate_up_proj.weight" : "ffns.22.up_proj.weight",
    "model.layers.22.mlp.down_proj.weight" : "ffns.22.down_proj.weight",
    "model.layers.22.input_layernorm.weight" : "sas.22.norm.weight",
    "model.layers.22.post_attention_layernorm.weight" : "ffns.22.norm.weight",
    "model.layers.23.self_attn.o_proj.weight" : "sas.23.out_proj.weight",
    "model.layers.23.self_attn.qkv_proj.weight" : "sas.23.qkv_proj.weight",
    "model.layers.23.mlp.gate_up_proj.weight" : "ffns.23.up_proj.weight",
    "model.layers.23.mlp.down_proj.weight" : "ffns.23.down_proj.weight",
    "model.layers.23.input_layernorm.weight" : "sas.23.norm.weight",
    "model.layers.23.post_attention_layernorm.weight" : "ffns.23.norm.weight",
    "model.layers.24.self_attn.o_proj.weight" : "sas.24.out_proj.weight",
    "model.layers.24.self_attn.qkv_proj.weight" : "sas.24.qkv_proj.weight",
    "model.layers.24.mlp.gate_up_proj.weight" : "ffns.24.up_proj.weight",
    "model.layers.24.mlp.down_proj.weight" : "ffns.24.down_proj.weight",
    "model.layers.24.input_layernorm.weight" : "sas.24.norm.weight",
    "model.layers.24.post_attention_layernorm.weight" : "ffns.24.norm.weight",
    "model.layers.25.self_attn.o_proj.weight" : "sas.25.out_proj.weight",
    "model.layers.25.self_attn.qkv_proj.weight" : "sas.25.qkv_proj.weight",
    "model.layers.25.mlp.gate_up_proj.weight" : "ffns.25.up_proj.weight",
    "model.layers.25.mlp.down_proj.weight" : "ffns.25.down_proj.weight",
    "model.layers.25.input_layernorm.weight" : "sas.25.norm.weight",
    "model.layers.25.post_attention_layernorm.weight" : "ffns.25.norm.weight",
    "model.layers.26.self_attn.o_proj.weight" : "sas.26.out_proj.weight",
    "model.layers.26.self_attn.qkv_proj.weight" : "sas.26.qkv_proj.weight",
    "model.layers.26.mlp.gate_up_proj.weight" : "ffns.26.up_proj.weight",
    "model.layers.26.mlp.down_proj.weight" : "ffns.26.down_proj.weight",
    "model.layers.26.input_layernorm.weight" : "sas.26.norm.weight",
    "model.layers.26.post_attention_layernorm.weight" : "ffns.26.norm.weight",
    "model.layers.27.self_attn.o_proj.weight" : "sas.27.out_proj.weight",
    "model.layers.27.self_attn.qkv_proj.weight" : "sas.27.qkv_proj.weight",
    "model.layers.27.mlp.gate_up_proj.weight" : "ffns.27.up_proj.weight",
    "model.layers.27.mlp.down_proj.weight" : "ffns.27.down_proj.weight",
    "model.layers.27.input_layernorm.weight" : "sas.27.norm.weight",
    "model.layers.27.post_attention_layernorm.weight" : "ffns.27.norm.weight",
    "model.layers.28.self_attn.o_proj.weight" : "sas.28.out_proj.weight",
    "model.layers.28.self_attn.qkv_proj.weight" : "sas.28.qkv_proj.weight",
    "model.layers.28.mlp.gate_up_proj.weight" : "ffns.28.up_proj.weight",
    "model.layers.28.mlp.down_proj.weight" : "ffns.28.down_proj.weight",
    "model.layers.28.input_layernorm.weight" : "sas.28.norm.weight",
    "model.layers.28.post_attention_layernorm.weight" : "ffns.28.norm.weight",
    "model.layers.29.self_attn.o_proj.weight" : "sas.29.out_proj.weight",
    "model.layers.29.self_attn.qkv_proj.weight" : "sas.29.qkv_proj.weight",
    "model.layers.29.mlp.gate_up_proj.weight" : "ffns.29.up_proj.weight",
    "model.layers.29.mlp.down_proj.weight" : "ffns.29.down_proj.weight",
    "model.layers.29.input_layernorm.weight" : "sas.29.norm.weight",
    "model.layers.29.post_attention_layernorm.weight" : "ffns.29.norm.weight",
    "model.layers.30.self_attn.o_proj.weight" : "sas.30.out_proj.weight",
    "model.layers.30.self_attn.qkv_proj.weight" : "sas.30.qkv_proj.weight",
    "model.layers.30.mlp.gate_up_proj.weight" : "ffns.30.up_proj.weight",
    "model.layers.30.mlp.down_proj.weight" : "ffns.30.down_proj.weight",
    "model.layers.30.input_layernorm.weight" : "sas.30.norm.weight",
    "model.layers.30.post_attention_layernorm.weight" : "ffns.30.norm.weight",
    "model.layers.31.self_attn.o_proj.weight" : "sas.31.out_proj.weight",
    "model.layers.31.self_attn.qkv_proj.weight" : "sas.31.qkv_proj.weight",
    "model.layers.31.mlp.gate_up_proj.weight" : "ffns.31.up_proj.weight",
    "model.layers.31.mlp.down_proj.weight" : "ffns.31.down_proj.weight",
    "model.layers.31.input_layernorm.weight" : "sas.31.norm.weight",
    "model.layers.31.post_attention_layernorm.weight" : "ffns.31.norm.weight",
    "model.norm.weight" : "norm.weight",
    "lm_head.weight" : "predictor.weight",
}

for hfmodel_name, hfmodel_param in hfmodel.named_parameters():

    assert(hfmodel_name in hfmodel_to_athena.keys())

    for athena_name, athena_param in athena.named_parameters():

        assert(athena_name in hfmodel_to_athena.values())

        if athena_name == hfmodel_to_athena[hfmodel_name]:

            assert(athena_param.shape == hfmodel_param.shape)

            athena_param.data.copy_(hfmodel_param.data)


print("Saving athena...")
torch.save(athena.state_dict(), "base.pt")